apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"my-pod"},"name":"my-pod","namespace":"default"},"spec":{"containers":[{"image":"nginx","name":"my-pod","volumeMounts":[{"mountPath":"/tmp/php.ini","name":"my-cm","subPath":"php.ini"}]}],"volumes":[{"configMap":{"name":"my-cm"},"name":"my-cm"}]}}
  creationTimestamp: "2025-04-07T07:05:59Z"
  labels:
    run: my-pod
  name: my-pod
  namespace: default
  resourceVersion: "1768387"
  uid: 2413957a-1de3-4e6d-8977-3e820722e424
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: my-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/php.ini
      name: my-cm
      subPath: php.ini
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lgnhl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: my-cm
    name: my-cm
  - name: kube-api-access-lgnhl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-07T07:06:01Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-04-07T07:05:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-04-07T07:06:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-04-07T07:06:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-04-07T07:05:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ef2832a9a8d78c11a51da8b7d602f0bf030173278c3ac9375b9a10ec3fc8ccfb
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:124b44bfc9ccd1f3cedf4b592d4d1e8bddb78b51ec2ed5056c52d3692baebc19
    lastState: {}
    name: my-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-04-07T07:06:01Z"
    volumeMounts:
    - mountPath: /tmp/php.ini
      name: my-cm
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lgnhl
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.65.3
  hostIPs:
  - ip: 192.168.65.3
  phase: Running
  podIP: 10.1.1.72
  podIPs:
  - ip: 10.1.1.72
  qosClass: BestEffort
  startTime: "2025-04-07T07:05:59Z"
