apiVersion: networking.k8s.io/v1  
kind: Ingress
metadata:
  name: argo-cd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: argo-cd
spec:
  ingressClassName: nginx
  rules:
  - host: argo-cd.local
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 80