apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-alertmanager
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: prometheus
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus-alertmanager.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-alertmanager
            port:
              number: 9093