apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-grafana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: prometheus
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus-grafana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
  - host: api-prometheus-grafana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 3000