apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:1.17.6
        volumeMounts:
        - name: cm-web
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      volumes:
      - name: cm-web
        configMap:
          name: cm-web