apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-web
  labels:
    release: prometheus
spec:
  jobName: blackbox-web
  prober:
    url: prometheus-blackbox-prometheus-blackbox-exporter.prometheus-blackbox.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - web.local # Ingress controller
        - web.web.svc.cluster.local # "web" service in the cluster
