apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-external
  labels:
    release: prometheus
spec:
  jobName: blackbox-external
  prober:
    url: prometheus-blackbox-prometheus-blackbox-exporter.prometheus-blackbox.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://dr.dk
        - https://tv2.dk
        - https://jp.dk
