apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-http
  namespace: monitoring
  labels:
    Release: prometheus
spec:
  jobName: blackbox-http
  prober:
    url: http://prometheus-blackbox-prometheus-blackbox-exporter.prometheus-blackbox.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://dr.dk
        - https://tv2.dk
